NAME     := ircserv
CXX      := c++
CXXFLAGS := -Wall -Wextra -Werror -std=c++98
INCLUDES := -Iincludes

SRCS := src/main.cpp src/Server.cpp src/Parser.cpp
OBJS := $(SRCS:.cpp=.o)

all: $(NAME)

$(NAME): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $^

src/%.o: src/%.cpp
	$(CXX) $(CXXFLAGS) $(INCLUDES) -c $< -o $@

clean:
	rm -f $(OBJS)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re
